const OrderHstoryTitle = [
    "SL NO.",
    "Operation",
    // "Docket No",
    // "Entry Type",
    // "Delivery Type",
    // "Cold Chain",
    // "Booking Date & Time",
    // "Type Of Booking",
    // "Delivery Mode",
    // "Bill To",
    // "Client",
    " Order Channel",
    "Type Of Booking",
    "Shipper Name",
    " Address",
    " State",
    " City",
    " Pincode",
    " Consignee Name",
    " Address",
    " State",
    " City",
    " Pincode",
    " Commodity",
    " COD",
    " Transportation cost",
    " Total Quantity",
    " Actual Weight",
    " Chargeable Weight",
    " Remarks",
    "Modified By",
    "Modified At",
]
export default OrderHstoryTitle