const OrganizationHistoryTableTitle = [
    "SL No.",
    "Operation",
    "Organization Name",
    "Email",
    "Toll Free Number",
    "Registration/Incorporation No",
    "PAN Number",
    " Primary Mobile No",
    "Secondary Mobile No",  
    "Website Address",
    "GST No",
    "City",
    "PinCode",
    "Locality",
    "Address",
    "H.O Address",
    "H.O State",
    "H.O City",
    "H.O Locality",
    "Contact Person",
    "Person Email",
    "Person Mo.No",
    "Discription",
    "Modified By",
    "Modified At", 
]
export default OrganizationHistoryTableTitle