const BranchHistoryTableTitle = [
  "SL NO.",
  "Operation",
  "Branch Code",
  "Branch Type",
  "Vendor Name",
  "Branch Name",
  "Branch Email",
  "Branch Phone Number",
  "PAN Number",
  "GST Number",
  "Operating City",
  "Address Line",
  "State",
  "City",
  "Pin Code",
  "Locality",
  "Branch Head",
  "Branch Head Email",
  "Branch Head Phone",
  "Modified By",
  "Modified At",
];

export default BranchHistoryTableTitle;
